In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

<h1>Data Intagration</h1>
<p>各地域のlistings,reviewsのコメント数上位N個を抜粋し、listings.csv,reviews.csvとして格納。</p>

In [ ]:
import pandas as pd

In [ ]:
import glob

In [ ]:
files = sorted(glob.glob("/content/drive/My Drive/input_data/listings/*.csv"))
listing_list = []
id_list = [] #抜粋した施設のidを格納。
print("listingデータの統合")
for i, path in enumerate(files):
    listing = pd.read_csv(path)
    listing_list.append(listing.sort_values('number_of_reviews',ascending=False)[:100]) #上位　50　個の施設を抜粋。
    id = listing.sort_values('number_of_reviews',ascending=False)[:100]["id"].values
    id_list.append(id)
    print(path,(i+1),"finished")
listings = pd.concat(listing_list)
for i in range(len(listing_list)):
    print((i+1),"番目のデータ：",listing_list[i].shape)
print("統合後：",listings.shape)

listingデータの統合
/content/drive/My Drive/input_data/listings/listings_chicago.csv 1 finished
/content/drive/My Drive/input_data/listings/listings_flolida.csv 2 finished
/content/drive/My Drive/input_data/listings/listings_hawai.csv 3 finished
/content/drive/My Drive/input_data/listings/listings_lasvegas.csv 4 finished
/content/drive/My Drive/input_data/listings/listings_losangeles.csv 5 finished
/content/drive/My Drive/input_data/listings/listings_nashville.csv 6 finished
/content/drive/My Drive/input_data/listings/listings_neworleans.csv 7 finished
/content/drive/My Drive/input_data/listings/listings_newyork.csv 8 finished
/content/drive/My Drive/input_data/listings/listings_sandiego.csv 9 finished
/content/drive/My Drive/input_data/listings/listings_sanf.csv 10 finished
1 番目のデータ： (100, 74)
2 番目のデータ： (100, 74)
3 番目のデータ： (100, 74)
4 番目のデータ： (100, 74)
5 番目のデータ： (100, 74)
6 番目のデータ： (100, 74)
7 番目のデータ： (100, 74)
8 番目のデータ： (100, 74)
9 番目のデータ： (100, 74)
10 番目のデータ： (100, 74)
統合後： (1000, 74)

In [ ]:
files = sorted(glob.glob("/content/drive/My Drive/input_data/reviews/*.csv"))
review_list = []
print("reviewデータの統合")
for i, path in enumerate(files):
    review = pd.read_csv(path)
    review_list.append(review.loc[review['listing_id'].isin(id_list[i])]) #id_listにある施設のレビューデータを抜粋。
    print(path,(i+1),"finished")
reviews = pd.concat(review_list)
for i in range(len(review_list)):
    print((i+1),"番目のデータ：",review_list[i].shape)
print("統合後：",reviews.shape)

reviewデータの統合
/content/drive/My Drive/input_data/reviews/reviews_chicago.csv 1 finished
/content/drive/My Drive/input_data/reviews/reviews_flolida.csv 2 finished
/content/drive/My Drive/input_data/reviews/reviews_hawai.csv 3 finished
/content/drive/My Drive/input_data/reviews/reviews_lasvegas.csv 4 finished
/content/drive/My Drive/input_data/reviews/reviews_losangeles.csv 5 finished
/content/drive/My Drive/input_data/reviews/reviews_nashville.csv 6 finished
/content/drive/My Drive/input_data/reviews/reviews_neworleans.csv 7 finished
/content/drive/My Drive/input_data/reviews/reviews_newyork.csv 8 finished
/content/drive/My Drive/input_data/reviews/reviews_sandiego.csv 9 finished
/content/drive/My Drive/input_data/reviews/reviews_sanf.csv 10 finished
1 番目のデータ： (36711, 6)
2 番目のデータ： (29675, 6)
3 番目のデータ： (37194, 6)
4 番目のデータ： (33057, 6)
5 番目のデータ： (52840, 6)
6 番目のデータ： (46627, 6)
7 番目のデータ： (35580, 6)
8 番目のデータ： (41924, 6)
9 番目のデータ： (44782, 6)
10 番目のデータ： (45251, 6)
統合後： (403641, 6)

In [ ]:
listings.to_csv("/content/drive/My Drive/input_data/listings.csv",index=False)
reviews.to_csv("/content/drive/My Drive/input_data/reviews.csv",index=False)

In [ ]:
reviews.groupby("listing_id").describe().shape

(1000, 16)

In [ ]:
loc_list = ["Chicago", "Miami", 'Hawaii', "Las Vegas", "Los an Angeles", "Nashvile", "New Orleans", "New York", "San Diego", "San Francisco"]

loc_id = pd.DataFrame({"id":[i for i in range(len(listings))],
                        "loc":[str(i) for i in range(len(listings))]})
i = 0
for j in range(len(loc_list)):
    for t in range(len(id_list[j])):
        loc_id['id'][i] = id_list[j][t]
        loc_id['loc'][i] = loc_list[j]
        i += 1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [ ]:
loc_id['loc'].value_counts()

Nashvile          100
Chicago           100
San Francisco     100
San Diego         100
Las Vegas         100
Miami             100
New York          100
Hawaii            100
Los an Angeles    100
New Orleans       100
Name: loc, dtype: int64

In [ ]:
loc_id.to_csv("/content/drive/My Drive/input_data/id_loc.csv",index=False)